### PR TITLE
Add GitHub Actions, fix minor issues (README, .bundleignore, etc)

### PR DESCRIPTION
**Pull request by r007**
Hey guys,

I added github actions for automatic release process. Steps required to make it work:

Step 1: Add secrets to repository settings:

- `SLACK_CHANNEL_WEBHOOK` (required): the Slack webhook URL that will be in your secrets.
- `REPO_PUBLISH_TOKEN` (required): personal access token, add it to your secrets.
- `SVN_USERNAME` (required): SVN username, used to deploy to WordPress.org repository.
- `SVN_PASSWORD` (required): SVN password, used to deploy to WordPress.org repository.

Step 2: [Create an initial release](https://github.com/sixach/wp-block-faq/releases/new) in GitHub. First version should be `1.0.0`, otherwise version will be reset back to `0.0.0`.

Other changes:
- README.md and readme.txt are merged. All the meta info is taken from `index.php` file.
- Fix typos in README.md (commas/dots)
- Add a couple more files to `.bundleignore`
- Add plugin meta fields to `index.php`
- Use WP-Scripts instead of linters (Stylelint/ESLint/etc)
- Automate WordPress.org deployments

### CODE REVIEW

**Comment by r007** [comment]
@kuserich Please help :) Can you please:
- Fix default branch on [wp-readme-generator-action](https://github.com/sixach/wp-readme-generator-action) (set it to `master`, I have no permissions).
- Make make it public? Otherwise it's not very convenient to copy action folder for every repository. Less copy-and-paste work.
- Add all the necessary secrets to repo settings.

**Comment by kuserich** [comment]
> @kuserich Please help :) Can you please:
> 
> * Fix default branch on [wp-readme-generator-action](https://github.com/sixach/wp-readme-generator-action) (set it to `master`, I have no permissions).
> * Make make it public? Otherwise it's not very convenient to copy action folder for every repository. Less copy-and-paste work.
> * Add all the necessary secrets to repo settings.

Thank you, @r007 . I have updated the default branch and I have changed the visibility of the repository to public and I yet need to add the secrets to the repo / organization.

However, before merging any of these changes, I would like to go through it again. I have to admit that it's not entirely clear to me what it does, how it works and how it's going to be used. Particularly because the changes that we introduce in this PR have some sideeffects on other files like `README.md`. I believe that this is important and required because whatever we do must i) work perfectly and ii) be properly defined as a standard.

Would you be able to elaborate on the process and also add some documentation in Notion?

**Comment by r007** [comment]
@kuserich Awesome! Thanks. I think I can remove local version now. Should be easier to understand when there is only ~10 files in PR and not 55 files.

About explanation... Alright, I'll try to explain as good as I can. The core idea itself is very simple: to merge `README.md` and `readme.txt` into single file. `Readme.txt` is just a normal readme file with theme/plugin meta properties on top of it. Meta properties we take from theme/plugin itself. Normally, whenever you update something - plugin description or stable tag or something else, need to update them in several places: `index.php`, `style.css` and `readme.txt`. But here, you can update it only in `index.php` and `readme.txt` will be generated on the fly. This allows you to concentrate on writing awesome text, instead of doing routine copy-and-paste from PHP file.

At the same time, this way you'll never forget to update metas everywhere.

On top of it, I added custom tag `<!-- only:github/ -->` which allows to keep two versions of README in a single file. One is for the developers, another one - for ordinary users. We hide all the development info from WordPress.org.

**Comment by kuserich** [comment]
Thanks for elaborating, @r007 . I think this would be a great feature to have and this would simplify our processes tremendously. However, at this point I'm afraid that we might be rushing into this solution without properly assessing and testing it first. Particularly, this PR includes additional changes that we have not peer-reviewed and verified yet. For instance, the changelog configs pretty much determine the structure of our changelogs (as well as a `CHANGELOG.md` file), the PR labeler appears not to be fully compatible with our previous definition, we are introducing workflows like auto-approve and auto-release, etc.

I do not feel comfortable deciding on so many critical components in a single PR without testing them first. Would we be able to isolate the changes and test them independently first?

**Comment by r007** [comment]
>Would we be able to isolate the changes and test them independently first?

@kuserich yeah, sure. I myself forked repository and tested every action on my own account. It worked fine. All the code been added from [github-actions](https://github.com/sixach/github-actions) repository, with slight adaptation. Not really rushed, because all the huge work been done previously. Now we can copy-and-paste all the code to every repository. Most projects are similar by structure with slight differences, such as branch naming is different (i.e. `main` in one place, `master` in another) etc.

**How to test it:**
1. Fork it to your own account @kuserich.
2. Merge `feature/github-actions` into `main`.
3. Add secrets.

**Release action:**
Go to `Actions -> Publish the Release`, click on `run` with any argument `patch`, `minor`, `major`. See the produced zip archive in github releases.

**Lint action:**
Try to create a new branch, open a new pull request. Add some linting errors, see files tab in PR.

**Notifications:**
Need to add slack webhook.

**Comment by r007** [comment]
@mahdiyazdani the reason why we introduced these actions - to simplify the process. Here's how it looks like right now:
1. Add some changes.
2. Bump version in `package.json`
3. Bump version in `index.php`
4. Install all the NPM, composer dependencies
4. Manually run `npm run bundle`
5. Create a new release on Github, attach a bundle. Type in some description.
6. Upload the bundle to WordPress.org.
7. Notify the team in slack.

How it looks with actions:
1. Add some changes.
2. Run the `Publish Release` action.

That's it! All the actions are gathered in one place [sixach/github-actions](https://github.com/sixach/github-actions) and can be replicated later to other repos. The reason why I'm adding them is because the more we use them, the more stable they become. I welcome discussion of any kind.

Some of the actions are unique and does not exist anywhere else:
[WP-Scripts Lint Action](https://github.com/sixach/wp-scripts-lint-action)
[WP Readme Generator Action](https://github.com/sixach/wp-readme-generator-action)
[WordPress Version Update](https://github.com/r007/gh-action-wordpress-version-update)

I believe that together they can form an ecosystem. As well as spread more awareness about sixa itself in developers community.

Also, this is a different kind of linting, with support of GitHub Annotations.
https://github.com/sixach/wp-scripts-lint-action/blob/master/.github/screenshots/check-annotations.png

Sorry, what do you mean by saying "not formatted by WP/Sixa standards"?

**Comment by gooklani** [comment]
Sometimes it would be better to prevent simplifying.
One time, the WooCommerce team released a version on the repository that caused a shocking break on users’ websites; that day was one of the worst days for WooCommerce developers. We have received a massive request for a refund. After just a couple of hours, they removed the update, but users were forced to update their database manually. So, it would be better to push updates manually to have enough time for reconsideration.

Also, @kuserich, I know it would be hard to write a changelog manually, but we can’t include all commits on the changelog. We need to have a solid and readable changelog. The plugin will review by a human in the big updates, and having a good changelog helps us.

**Pull request closed without merging**
